language: python
python:
  - "3.7"

# command to install dependencies
install:
  - "pip install pytest python-telegram-bot==12.0.0 requests==2.18.4 retrying==1.3.3 google-cloud-firestore==1.6.0"

# command to run tests
script:
  - python run_tests.py
